# Generated by Django 2.2.3 on 2020-05-30 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_items', to='ordersapp.ClientCard')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersapp.CalendarDate')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersapp.TimePeriod')),
            ],
        ),
    ]
