# Generated by Django 2.2.3 on 2020-06-04 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_service'),
        ('ordersapp', '0002_carditem_clientcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersapp.CalendarDate')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersapp.TimePeriod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
