# Generated by Django 2.2.3 on 2020-06-12 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcard',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='создан'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcard',
            name='card_number',
            field=models.SlugField(max_length=4, unique=True),
        ),
    ]
