# Generated by Django 2.2.3 on 2020-06-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0004_auto_20200612_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcard',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активен'),
        ),
    ]
