from myfitbot.config import server_name


url_cat = server_name + 'api/v1/services/servicecategories/'
url_servs = server_name + 'api/v1/services/category/'
url_serv = server_name + 'api/v1/services/service/'
url_crt_date = server_name + 'api/v1/orders/create/date/'
url_dats = server_name + 'api/v1/orders/dates/'
url_date = server_name + 'api/v1/orders/date/'
url_pers = server_name + 'api/v1/orders/periods/'
url_per = server_name + 'api/v1/orders/period/'
url_ordr = server_name + 'api/v1/orders/create/order/'
url_bskt = server_name + 'api/v1/orders/create/basket/'
url_baskt = server_name + 'api/v1/orders/basket/'
url_bsk_all = server_name + 'api/v1/orders/basket/all/'
url_bsk_clr = server_name + 'api/v1/orders/basket/del/'
url_crt_card = server_name + 'api/v1/orders/create/card/'
url_card = server_name + 'api/v1/orders/card/'
url_cards = server_name + 'api/v1/orders/card/all/'
url_reg = server_name + 'api/v1/rest-auth/registration/'
url_tok = server_name + 'api/v1/rest-auth/login/'
url_out = server_name + 'api/v1/rest-auth/logout/'
url_act = server_name + 'api/v1/orders/card/activate/'
url_email = server_name + 'api/v1/orders/email/'
